#!/bin/bash

shopt -s lastpipe
removedups () 
{ 
    f=$(mktemp);
    awk '!x[$0]++' "$1" > "$f";
    mv "$f" "$1"
}

path ()
{
find $(echo $PATH | tr ':' ' ') -type f -executable | sed 's/^.*\///g'
}


## make a temporary file to list all commands
p=$(mktemp)
## add some personal commands first (on the top)
cat $HOME/.config/shortcuts > "$p"
## add all commands from path
path >> "$p"
## remove duplicates
removedups "$p" 
## choose command to execute using fzy (if run from terminal) or rofi (if run using window-manager shortcut)
if [[ $TERM = linux && -n $DISPLAY ]]; then
	 rofi -dmenu -font "Noto Sans Mono Medium 18" -input $p | read command
else
	fzy < $p | read command 
#	fzf --reverse --height 10 < $p | read command 
fi
## run the command
exec $command &
